// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package dev.jvmguard.integration.tests.jvmguard.classes.rmi;

@SuppressWarnings("deprecation")
public final class MyRemote1Impl_Stub
    extends java.rmi.server.RemoteStub
    implements MyRemote1
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("java.lang.String simpleCall(java.lang.String)")
    };
    
    private static final long interfaceHash = -2975974539238779073L;
    
    private static final long serialVersionUID = 2;
    
    private static boolean useNewInvoke;
    private static java.lang.reflect.Method $method_simpleCall_0;
    
    static {
	try {
	    java.rmi.server.RemoteRef.class.getMethod("invoke",
		new Class[] {
		    java.rmi.Remote.class,
		    java.lang.reflect.Method.class,
		    Object[].class,
		    long.class
		});
	    useNewInvoke = true;
	    $method_simpleCall_0 = MyRemote1.class.getMethod("simpleCall", new Class[] {String.class});
	} catch (NoSuchMethodException e) {
	    useNewInvoke = false;
	}
    }

    // constructors
    public MyRemote1Impl_Stub() {
	super();
    }
    public MyRemote1Impl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }

    // methods from remote interfaces

    // implementation of simpleCall(String)

    @Override
    public String simpleCall(String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    if (useNewInvoke) {
		Object $result = ref.invoke(this, $method_simpleCall_0, new Object[] {$param_String_1}, -9013370514582644239L);
		return ((String) $result);
	    } else {
		java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 0, interfaceHash);
		try {
		    java.io.ObjectOutput out = call.getOutputStream();
		    out.writeObject($param_String_1);
		} catch (java.io.IOException e) {
		    throw new java.rmi.MarshalException("error marshalling arguments", e);
		}
		ref.invoke(call);
		String $result;
		try {
		    java.io.ObjectInput in = call.getInputStream();
		    $result = (String) in.readObject();
		} catch (java.io.IOException e) {
		    throw new java.rmi.UnmarshalException("error unmarshalling return", e);
		} catch (ClassNotFoundException e) {
		    throw new java.rmi.UnmarshalException("error unmarshalling return", e);
		} finally {
		    ref.done(call);
		}
		return $result;
	    }
	} catch (RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
