name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/gradle-test.yml
    with:
      tasks: test :integration:citest :ui:e2eTest
      timeout-minutes: 90
      playwright: true
